### ISSUE TITLE
Image Cannot change

### ISSUE THREAD

**Issue by Dedy54** [Jcowwell/Custom-Tab-Bar-Example#1]
Hi man, actually i am newbie on iOS programming, i just clone your project, and then i already read the this tutorial too https://github.com/codepath/ios_guides/wiki/Creating-a-Custom-Tab-Bar. Now i try to implement on my project, but i got problem when i clicked the button icon, it will gone. my question is why my button cannot change too normal icon, after i clicked on the button ? and i already too make 2 type of icon selected="A", deselected="A-Deselected". I see in your project you have 2 type of icon. selected and deselected. 

thanks man,

**Comment by Jcowwell** [comment]
Is your deslected ​icon set as the default image under the defatlt​ state configuratio and the selected icon set under the selcted ​state Configuarationn in the Interface Builder when you open storyboard?
![screen shot 2017-02-15 at 3 37 22 pm](https://cloud.githubusercontent.com/assets/20213661/22994416/dfdcb928-f394-11e6-9d88-8aa28c9cf2be.png)
![screen shot 2017-02-15 at 3 37 14 pm](https://cloud.githubusercontent.com/assets/20213661/22994418/dfeb04b0-f394-11e6-8d14-8405677d074d.png)

**Comment by Dedy54** [comment]
oh mannn, you save my life, thanks @Jcowwell
